id: IF7004EA5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:51:15+00:00'
last_modified: '2022-06-08T06:18:25.339602+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9593
  title: རྟ་མགྲིན་པདྨ་ཡང་གསང་ཁྲོས་པའི་ཆོས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CC77:
      image_group_id: I1KG9639
      title: ''
      total_pages: 642
      order: 1
      base_file: CC77.txt
    F86C:
      image_group_id: I1KG9640
      title: ''
      total_pages: 558
      order: 2
      base_file: F86C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
